openapi: 3.0.1
info:
  title: "API Coder Backend - Users"
  version: "1.0.0"
  description: "API Documentation for User Management and Authentication"
tags:
  - name: auth
    description: "Operations related to user registration, authentication, and session management"

paths:
  /api/register:
    post:
      tags:
        - auth
      summary: "Register a new user"
      description: "Allows registering a user by providing necessary information."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                  description: "User's first name"
                lastName:
                  type: string
                  description: "User's last name"
                email:
                  type: string
                  format: email
                  description: "User's unique email address"
                age:
                  type: integer
                  description: "User's age"
                password:
                  type: string
                  format: password
                  description: "User's password"
                role:
                  type: string
                  description: "User's role (e.g., 'user' or 'admin')"
              required:
                - firstName
                - lastName
                - email
                - age
                - password
                - role
            example:
              firstName: "John"
              lastName: "Doe"
              email: "johnDoe@example.com"
              age: 18
              password: "password1"
              role: "user"
      responses:
        "201":
          description: "User registered successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User registered successfully"
        "400":
          description: "Bad request, user already registered"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User already registered"
        "500":
          description: "Internal server error"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "An unknown error occurred"

  /api/login:
    post:
      tags:
        - auth
      summary: "User login"
      description: "Allows the user to log in by providing valid credentials."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: "User's registered email address"
                password:
                  type: string
                  format: password
                  description: "User's password"
              required:
                - email
                - password
            example:
              email: "johnDoe@example.com"
              password: "password1"
      responses:
        "200":
          description: "Login successful"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Logged in successfully"
                  token:
                    type: string
                    example: "jwt.token.example"
        "401":
          description: "Invalid credentials"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid email or password"
        "500":
          description: "Internal server error"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "An unknown error occurred"

  /api/sessions/current:
    get:
      tags:
        - auth
      security:
        - jwt: []
      summary: "Get the current user's session"
      description: "Retrieve the authenticated user's data using the provided JWT token."
      responses:
        "200":
          description: "User data fetched successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  firstName:
                    type: string
                    example: "John"
                  lastName:
                    type: string
                    example: "Doe"
                  email:
                    type: string
                    format: email
                    example: "johnDoe@example.com"
                  age:
                    type: integer
                    example: 18
                  role:
                    type: string
                    example: "user"
        "401":
          description: "Unauthorized or invalid token"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Unauthorized or invalid token"
        "500":
          description: "Internal server error"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "An unknown error occurred"

components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
